record_path = "C:/Users/lorenz/Desktop/angelo_lab/MIBI_test/TNBC_CD45.tfrecord"
path = "C:/Users/lorenz/OneDrive/Desktop/angelo_lab/"
experiment = "test"
project = "Nimbus"
logging_mode = "offline"
model = "ModelBuilder"
num_steps = 20
lr = 1e-5
terminal_lr = 5e-7
backbone = "VanillaUNet"
dataset_names = ["TNBC_CD45"]
dataset_sample_probs = [1.0]
input_shape = [256,256,4]
batch_constituents = ["mplex_img", "binary_mask", "nuclei_img", "membrane_img"]
num_validation = [3]
num_test = [3]
shuffle_buffer_size = 2000
flip_prob = 0.5
affine_prob = 0.25
scale_min = 0.8
scale_max = 1.2
shear_angle = 0.2
elastic_prob = 0.25
elastic_alpha = 10
elastic_sigma = 4
rotate_prob = 0.5
rotate_count = 3
gaussian_noise_prob = 0.25
gaussian_noise_min = 0.001
gaussian_noise_max = 0.015
gaussian_blur_prob = 0.25
gaussian_blur_min = 0.05
gaussian_blur_max = 0.15
contrast_prob = 0.25
contrast_min = 0.8
contrast_max = 1.2
mixup_prob = 0.0
mixup_alpha = 4.0
batch_size = 4
loss_fn = "BinaryCrossentropy"
use_mixed_precision = false
loss_selective_masking = true
quantile = 0.5
quantile_end = 0.9
quantile_warmup_steps = 100000
confidence_thresholds = [0.1, 0.9]
ema = 0.01
gradient_clipping = 1.0
location = false

[loss_kwargs]
from_logits = false
label_smoothing = 0.05
class_weight=0.5

[classes]
marker_positive = 1
